### ISSUE TITLE
Add 'About' page

### ISSUE THREAD

**Issue by andrico1234** [andrico1234/calisthenics-skills#56]
Make an SEO friendly about us page.

### Part I
- [x] Draw up some sketches about what the Page should look like
- [x] Use accordions to not overwhelm the reader with text. Allow all text to load when the site does, for SEO purposes
- [x] Pull in the data from the 'about' data object. Each item in the arrow should be contained within the accordion, with the title being the title of the accordion.
- [x] Style the accordion as necessary

### Part II
- [x] Split up the About page into components
- [x] Finish adding content
- [x] Find a way to gracefully add images to the content block

### Part IV
- [x] Use the SEO component in the page
- [x] Research some useful keywords, including long-tail keywords.

https://springload.github.io/react-accessible-accordion/ use this, but change the style so that it fits with the rest of the site. 

Implementation first, style second
